image: Visual Studio 2017
configuration:
 - Debug
 - Release
before_build:
 - ps: nuget restore
notifications:
 - provider: Email
    to: scatena.guido@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
